event:
    resource: "@EventBundle/Resources/config/routing.yml"
    prefix:   /

register_user:
    pattern: /register
    defaults:  { _controller: UserBundle:Register:register }

login_form:
    path: /login
    defaults:  { _controller: UserBundle:Security:login }

logout:
    path: /logout
    defaults:  { _controller: UserBundle:Security:logout }

login_check:
    pattern:   /login_check
    defaults:  { _controller: UserBundle:Security:loginCheck }

