<?php

namespace Yoda\EventBundle\Repository;

use Yoda\EventBundle\Entity\Event;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends \Doctrine\ORM\EntityRepository
{
    public function getUpcominEvents($max = null){
        $query = $this->createQueryBuilder('e')
                    ->addOrderBy('e.time', 'ASC')
                    ->andWhere('e.time > :now')
                    ->setParameter('now', new \DateTime());
        if($max){
            $query->setMaxResults($max);
        }
        return $query
                    ->getQuery()
                    ->execute();
    }

    /**
     * @return Event[]
     */
    public function getRecentUpdatedEvents(){
        $query = $this->createQueryBuilder('e')
                    ->andWhere('e.createdAt > :since')
                    ->setParameter('since', new \DateTime('24 hours ago'))
                    ->getQuery()
                    ->execute();
        return $query;
    }
}
